=== convince-project/data-model/data-format-specifications/RoAML/main.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="roaml">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="mc_parameters">
					<xs:complexType>
						<xs:all>
							<xs:element name="max_time">
								<xs:complexType>
									<xs:attribute name="value" type="xs:integer"/>
									<xs:attribute name="unit" type="xs:string"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="bt_tick_rate">
								<xs:complexType>
									<xs:attribute name="value" type="xs:float"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="bt_tick_if_not_running" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="value" type="xs:boolean"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="max_array_size" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="value" type="xs:integer"/>
								</xs:complexType>
							</xs:element>
						</xs:all>
					</xs:complexType>
				</xs:element>
				<xs:element name="behavior_tree">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="input" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="type" type="xs:string"/>
									<xs:attribute name="src" type="xs:string"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="node_models">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="input" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="type" type="xs:string"/>
									<xs:attribute name="src" type="xs:string"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="properties">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="input">
								<xs:complexType>
									<xs:attribute name="type" type="xs:string"/>
									<xs:attribute name="src" type="xs:string"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>

				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>


</xs:schema>

=== convince-project/data-model/examples/UC1-vacuum-cleaner/high-level-models/main.xml
<?xml version="1.0" encoding="UTF-8"?>
<roaml
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../../data-format-specifications/RoAML-XML/main.xsd">

    <mc_parameters>
        <max_time value="40" unit="s" />
        <bt_tick_rate value="5.0" />
        <bt_tick_if_not_running value="true" />
    </mc_parameters>

    <behavior_tree>
        <input type="bt.cpp-xml" src="./bt_policies/policy.xml" />
        <input type="bt-plugin-ascxml" src="./bt_plugins/bt_perform_docking_maneuver.scxml" />
        <input type="bt-plugin-ascxml" src="./bt_plugins/bt_simple_wait.scxml" />
        <input type="bt-plugin-ascxml" src="./bt_plugins/bt_is_charging.scxml" />
        <input type="bt-plugin-ascxml" src="./bt_plugins/bt_reset_bumper_state.scxml" />
        <input type="bt-plugin-ascxml" src="./bt_plugins/bt_back_up.scxml" />
        <input type="bt-plugin-ascxml" src="./bt_plugins/bt_is_bump_detected.scxml" />
    </behavior_tree>

    <node_models>
        <input type="node-ascxml" src="./nodes/robot_model.scxml" />
    </node_models>

    <properties>
        <input type="jani" src="./properties/properties.jani" />
    </properties>
</roaml>
